accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

app_name = 'accounts'

urlpatterns = [
    path('sign-in', views.SignInView.as_view(), name='sign_in'),
    path('sign-up', views.SignUpView.as_view(), name='sign_up'),
    path('sign-out', LogoutView.as_view(), name='sign_out'),
    path('reset-password', views.AccountsResetPasswordView.as_view(), name='reset_password'),
    path('reset-password-done', views.AccountsResetPasswordDoneView.as_view(), name='reset_password_done'),
    path('reset-password-confirm/<str:uidb64>/<str:token>/', views.AccountsResetPasswordConfirmView.as_view(), name='reset_password_confirm'),
    path('reset-password-complete/', views.AccountsResetPasswordCompleteView.as_view(), name='reset_password_complete'),
    path('sign-up-started', views.SignUpStartedView.as_view(), name='sign_up_started'),
    path('complete-signup/<uuid:token>', views.CompleteSignUpView.as_view(), name='complete_signup'),

]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('browse', views.BrowseTemplateView.as_view(), name='browse'),
    path('shelves', views.ShelvesTemplateView.as_view(), name='shelves'),
    path('wishlist', views.WishlistTemplateView.as_view(), name='wishlist'),
    path('friends', views.FriendsTemplateView.as_view(), name='friends'),
    path('chat', views.ChatTemplateView.as_view(), name='chat'),
    path('profile', views.ProfileTemplateView.as_view(), name='profile'),
    path('settings', views.SettingsTemplateView.as_view(), name='settings'),
]

readwise/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('core.urls')),
]

accounts/models.py
from uuid import uuid4
import datetime as dt

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.core.mail import send_mail
from django.conf import settings

from readwise.models import TimestampedModel

from .managers import CreateAccountRequestManager

class ReadWiseUser(AbstractUser):
    """
    This is the custom user model for all ReadWise users.
    """
    ...

class CreateAccountRequest(TimestampedModel):
    """
    Represents the information the user sends when they 
    create an account before email verification.
    """
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    username = models.CharField(max_length=255)
    email = models.EmailField()
    password = models.CharField(max_length=255)
    token = models.UUIDField(default=uuid4)
    is_token_used = models.BooleanField(default=False)

    objects = CreateAccountRequestManager()

    def create_account(self) -> ReadWiseUser:
        """
        Creates a ``ReadWise`` account from the registration request.
        Throws a `ValueError` if the request is invalid or another user
        has been saved with the email/username.
        """

        # assert request validity.
        if not self.is_valid():
            raise ValueError('The request has expired or is invalid')

        # assert the username uniqueness
        if ReadWiseUser.objects.filter(username=self.username).exists():
            raise ValueError(f'The username: {self.username} is taken.')
        
        # assert email uniqueness
        if ReadWiseUser.objects.filter(email=self.email).exists():
            raise ValueError(f'The email: {self.email} is taken.')
        
        # mark the as used.
        self.mark_used()
        
        # create the readwise user
        return ReadWiseUser.objects.create(
            email=self.email,
            password=self.password,
            first_name=self.first_name,
            last_name=self.last_name,
            username=self.username
        )


    def is_valid(self) -> bool:
        """
        Checks whether the request is valid. A valid request satisfies the following:-
        - The token hasn't been used before.
        - The token hasn't expired.

        :return: Whether the current request is valid.
        """

        # Token has been used - invalid.
        if self.is_token_used:
            return False

        # Token has expired
        exp_duration_secs = settings.SIGN_UP_TOKEN_EXPIRATION_DURATION_SECS
        expiration_date = self.created_at + dt.timedelta(seconds=exp_duration_secs)
        if timezone.now() > expiration_date:
            return False
        
        return True
    
    def mark_used(self) -> None:
        """
        Mark this request as used.
        """

       # token is marked as used already.
        if self.is_token_used:
            return

        # mark the token as used.
        self.is_token_used = True
        self.save(update_fields=['is_token_used'])
    
    def send_registration_email(self) -> None:
        """
        Send registration email.
        """
        base_url = settings.BASE_URL
        signup_url = f"{base_url}/accounts/complete-signup/{self.token}"

        message = (
            "Welcome to ReadWise!\n\n"
            "Thanks for signing up. To complete your registration, please click "
            "the link below:\n\n"
            f"{signup_url}\n\n"
            "If you did not request this account, you can safely ignore this email.\n\n"
            "— The ReadWise Team"
        )

        send_mail(
            subject='ReadWise Sign Up',
            from_email='admin@readwise.com',
            message=message,
            recipient_list=[self.email]
        )

accounts/forms.py
from django import forms
from .models import ReadWiseUser

class CreateAccountRequestForm(forms.Form):
    first_name = forms.CharField(max_length=255)
    last_name = forms.CharField(max_length=255)
    username = forms.CharField(max_length=255)
    email = forms.EmailField()
    password = forms.CharField(max_length=50)
    confirm_password = forms.CharField(max_length=50)

    def clean_password(self) -> str:
        password = self.cleaned_data.get('password', '')
        if len(password) < 8:
            raise forms.ValidationError('Password should have a minimum of 8 characters.')
        return password
    
    def clean_confirm_password(self) -> str:
        password = self.cleaned_data.get('password', '')
        confirm_password = self.cleaned_data.get('confirm_password', '')
        
        if password != confirm_password:
            raise forms.ValidationError('The passwords do not match.')
        
        return confirm_password
    
    def clean_email(self) -> str:
        email = self.cleaned_data.get('email', '')

        if ReadWiseUser.objects.filter(email=email).exists():
            raise forms.ValidationError('This email is taken.')

        return email
    
    def clean_username(self) -> str:
        username = self.cleaned_data.get('username', '')
        
        if ReadWiseUser.objects.filter(username=username).exists():
            raise forms.ValidationError('Username is taken.')
        
        return username

accounts/views.py
import uuid
import logging

from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.views.generic import TemplateView, FormView
from django.views import View
from django.contrib.auth.views import (
    LoginView, PasswordResetView, PasswordResetDoneView,
    PasswordResetConfirmView, PasswordResetCompleteView
)
from django.urls import reverse, reverse_lazy
from django.contrib.messages import error, success
from django.contrib.auth import login

from .forms import CreateAccountRequestForm
from .models import CreateAccountRequest

logger = logging.getLogger(__name__)

class SignInView(LoginView):
    template_name = 'accounts/sign_in.html'

class SignUpView(FormView):
    template_name = 'accounts/sign_up.html'
    form_class = CreateAccountRequestForm
    success_url = reverse_lazy('accounts:sign_up_started')

    def form_valid(self, form):
        # Save the registration request to db.
        request = CreateAccountRequest.objects.create_request(
            first_name=form.cleaned_data.get('first_name'),
            last_name=form.cleaned_data.get('last_name'),
            username=form.cleaned_data.get('username'),
            email=form.cleaned_data.get('email'),
            password=form.cleaned_data.get('password'),
        )

        # Send registration email.
        request.send_registration_email()

        return super().form_valid(form)

class AccountsResetPasswordView(PasswordResetView):
    template_name = 'accounts/reset_password.html'
    success_url = reverse_lazy('accounts:reset_password_done')

    # email configuration
    from_email = 'inotifiers@gmail.com'
    email_template_name = 'accounts/reset_password_email.txt'
    subject_template_name = 'accounts/reset_password_subject.txt'

class AccountsResetPasswordDoneView(PasswordResetDoneView):
    template_name = 'accounts/reset_password_done.html'

class AccountsResetPasswordConfirmView(PasswordResetConfirmView):
    template_name = 'accounts/reset_password_confirm.html'
    success_url = reverse_lazy('accounts:reset_password_complete')

class AccountsResetPasswordCompleteView(PasswordResetCompleteView):
    template_name = 'accounts/reset_password_complete.html'

class SignUpStartedView(TemplateView):
    template_name = 'accounts/sign_up_started.html'


class CompleteSignUpView(View):
    def get(self, req: HttpRequest, token: uuid.UUID) -> HttpResponse:
        # retrieve the request
        request = CreateAccountRequest.objects.filter(token=token).first()

        # assert the request exists.
        if not request:
            error(req, "The link is invalid or has expired")
            return HttpResponseRedirect(reverse('accounts:sign_in'))

        # attempt to create an account 
        try:
            user = request.create_account()
        except ValueError as e:
            error(req, "The link is invalid or has expired.")
            logger.exception(e)
            return HttpResponseRedirect(reverse('accounts:sign_in'))
        
        # log the user in automatically
        success(req, 'Sign up was successful!')
        login(req, user)
        return HttpResponseRedirect(reverse('core:browse'))

accounts/templates/accounts/base.html
{% extends 'base.html' %}

{% block body %} 

    <nav class="navbar bg-primary" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">
            <i class="bi bi-book"></i>
            <span class="ms-2">ReadWise</span>
            </a>
        </div>
    </nav>

    <h2 class="text-center mt-5">
        {% block accounts_title %}{% endblock accounts_title %}
    </h2>

    {% block accounts_body %} {%endblock accounts_body %}

{% endblock body %}

accounts/templates/accounts/reset_password.html
{% extends 'accounts/base.html' %}

{% block title %} Forgot Password {% endblock title %}

{% block accounts_title %} Reset Your Password {% endblock accounts_title %}

{% block accounts_body %} 

<div class="d-flex justify-content-center mt-2">
    <div style="width: 100%; max-width: 400px;">
        <form class="p-4 border rounded" method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label for="email" class="form-label">Email</label>
                <input type="email" class="form-control" id="email" name="email">
                {% for error in form.email.errors %}
                    <small class="text-danger">{{ error }}</small>
                {% endfor%}
            </div>

            <button type="submit" class="btn btn-primary w-100">Reset</button>
        </form>

        <div class="d-flex justify-content-center mt-3 px-1">
            <a href="{% url 'accounts:sign_in' %}">Already know your password? Sign In</a>
        </div>
    </div>
</div>

{% endblock accounts_body %}

accounts/templates/accounts/reset_password_complete.html
{% extends 'accounts/base.html' %}

{% block title %} Reset Password Complete {% endblock title %}

{% block accounts_title %} Reset Password Complete {% endblock accounts_title %}

{% block accounts_body %} 

<div class="d-flex justify-content-center mt-2">
    <div style="width: 100%; max-width: 400px;">
        <div class="alert alert-info">Your password was reset successfully. Please sign in.</div>
        <div class="d-flex justify-content-center mt-3 px-1">
            <a class="btn btn-primary w-100" href="{% url 'accounts:sign_in' %}"> Sign In</a>
        </div>
    </div>
</div>

{% endblock accounts_body %}

accounts/templates/accounts/reset_password_confirm.html
{% extends 'accounts/base.html' %}

{% block title %} Reset Password {% endblock title %}

{% block accounts_title %} Reset Your Password {% endblock accounts_title %}

{% block accounts_body %} 

<div class="d-flex justify-content-center mt-2">

    <div style="width: 100%; max-width: 400px;">

        {% if form %}
            <div class="alert alert-primary d-flex align-items-center" role="alert">
                <i class="bi bi-info-circle"></i>
                <div class="ms-2">
                    Enter your new password. You will automatically be logged in.
                </div>
            </div>

            <form class="p-4 border rounded" method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="new_password1" class="form-label">Password</label>
                    <input type="password" class="form-control" id="new_password1" name="new_password1">
                    {% for error in form.new_password1.errors %}
                        <small class="text-danger">{{ error }}</small>
                    {% endfor %}
                </div>

                <div class="mb-3">
                    <label for="new_password2" class="form-label">Confirm Password</label>
                    <input type="password" class="form-control" id="new_password2" name="new_password2">
                    {% for error in form.new_password2.errors %}
                        <small class="text-danger">{{ error }}</small>
                    {% endfor %}
                </div>

                <button type="submit" class="btn btn-primary w-100">Reset</button>
            </form>
        {% else %}
            <div class="alert alert-danger d-flex align-items-center" role="alert">
                <i class="bi bi-info-circle"></i>
                <div class="ms-2">
                    The reset password link is invalid or has expired.
                </div>
            </div>
        {% endif %}

        <div class="d-flex justify-content-center mt-3 px-1">
            <a href="{% url 'accounts:sign_in' %}">Already know your password? Sign In</a>
        </div>
    </div>
</div>

{% endblock accounts_body %}

accounts/templates/accounts/reset_password_done.html
{% extends 'accounts/base.html' %}

{% block title %} Reset Password Done {% endblock title %}

{% block accounts_title %} Reset Password Done {% endblock accounts_title %}

{% block accounts_body %} 

<div class="d-flex justify-content-center mt-2">
    <div style="width: 100%; max-width: 400px;">
        <div class="alert alert-info">An email has been sent with a link to reset your password.</div>
        <div class="d-flex justify-content-center mt-3 px-1">
            <a class="btn btn-primary w-100" href="{% url 'accounts:sign_in' %}">Already know your password? Sign In</a>
        </div>
    </div>
</div>

{% endblock accounts_body %}

accounts/templates/accounts/sign_in.html
{% extends 'accounts/base.html' %}

{% block title %} Sign In {% endblock title %}

{% block accounts_title %} Sign In {% endblock accounts_title %}

{% block accounts_body %} 


<div class="d-flex justify-content-center mt-2">
    <div style="width: 100%; max-width: 400px;">

        {% if form.errors %}
            <div class="alert alert-danger">Invalid Credentials</div>
        {% endif %}

        <form class="p-4 border rounded" method="post">
            {% csrf_token %}

            <div class="mb-3">
                <label for="username" class="form-label">Username</label>
                <input type="text" class="form-control" id="username" name="username">
            </div>

            <div class="mb-3">
                <label for="password" class="form-label">Password</label>
                <input type="password" class="form-control" id="password" name="password">
            </div>

            <div class="mb-3 form-check">
                <input type="checkbox" class="form-check-input" id="remember">
                <label class="form-check-label" for="remember">Remember Me</label>
            </div>

            <button type="submit" class="btn btn-primary w-100">Sign In</button>
        </form>

        <div class="d-flex justify-content-between mt-3 px-1">
            <a href="{% url 'accounts:reset_password' %}">Forgot Password?</a>
            <a href="{% url 'accounts:sign_up' %}">Don’t have an account? Register</a>
        </div>

    </div>
</div>

{% endblock accounts_body %}

accounts/templates/accounts/sign_up.html
{% extends 'accounts/base.html' %}

{% block title %} Sign Up {% endblock title %}

{% block accounts_title %} Create an Account {% endblock accounts_title %}

{% block accounts_body %} 

<div class="d-flex justify-content-center mt-2">
    <div style="width: 100%; max-width: 400px;">

        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                Please correct the errors below.
            </div>
        {% endif %}

        <form class="p-4 border rounded" method='post' action="{% url 'accounts:sign_up' %}">
            {% csrf_token %}

            <div class="mb-3">
                <label for="first_name" class="form-label">First Name</label>
                <input type="text" class="form-control" id="first_name" name="first_name" value="{{form.first_name.value|default:''}}">
                {% for error in form.errors.first_name %}
                    <small class="text-danger">{{ error }}</small>
                {% endfor %}
            </div>

            <div class="mb-3">
                <label for="last_name" class="form-label">Last Name</label>
                <input type="text" class="form-control" id="last_name" name="last_name" value="{{form.last_name.value|default:'' }}">
                {% for error in form.errors.last_name %}
                    <small class="text-danger">{{ error }}</small>
                {% endfor %}
            </div>

            <div class="mb-3">
                <label for="username" class="form-label">Username</label>
                <input type="text" class="form-control" id="username" name="username" value="{{form.username.value|default:'' }}">
                {% for error in form.errors.username %}
                    <small class="text-danger">{{ error }}</small>
                {% endfor %}
            </div>

            <div class="mb-3">
                <label for="email" class="form-label">Email</label>
                <input type="email" class="form-control" id="email" name="email" value="{{form.email.value|default:'' }}">
                {% for error in form.errors.email %}
                    <small class="text-danger">{{ error }}</small>
                {% endfor %}
            </div>

            <div class="mb-3">
                <label for="password" class="form-label">Password</label>
                <input type="password" class="form-control" id="password" name="password">
                {% for error in form.errors.password %}
                    <small class="text-danger">{{ error }}</small>
                {% endfor %}
            </div>

            <div class="mb-3">
                <label for="confirm_password" class="form-label">Confirm Password</label>
                <input type="password" class="form-control" id="confirm_password" name="confirm_password">
                {% for error in form.errors.confirm_password %}
                    <small class="text-danger">{{ error }}</small>
                {% endfor %}
            </div>

            <button type="submit" class="btn btn-primary w-100">Sign Up</button>

        </form>

        <div class="d-flex justify-content-center mt-3 px-1">
            <a href="{% url 'accounts:sign_in' %}">Already have an account? Sign In</a>
        </div>
    </div>
</div>

{% endblock accounts_body %}

accounts/templates/accounts/sign_up_started.html
{% extends 'accounts/base.html' %}

{% block title %} Sign Up Started {% endblock title %}

{% block accounts_title %} Complete Sign Up {% endblock accounts_title %}

{% block accounts_body %} 

<div class="d-flex justify-content-center mt-2">
    <div style="width: 100%; max-width: 400px;">

        <div class="alert alert-info p-4 mb-4" role="alert">
            <p class="mb-4">Thank you for starting the sign-up process! Please check your email for a confirmation link to complete your registration.</p>
        </div>

        <a type="submit" href="{% url 'accounts:sign_in' %}" class="btn btn-primary w-100">Back to Home</a>

    </div>
</div>

{% endblock accounts_body %}