accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

app_name = 'accounts'

urlpatterns = [
    path('sign-in', views.SignInView.as_view(), name='sign_in'),
    path('sign-up', views.SignUpView.as_view(), name='sign_up'),
    path('sign-out', LogoutView.as_view(), name='sign_out'),
    path('reset-password', views.AccountsResetPasswordView.as_view(), name='reset_password'),
    path('reset-password-done', views.AccountsResetPasswordDoneView.as_view(), name='reset_password_done'),
    path('reset-password-confirm/<str:uidb64>/<str:token>/', views.AccountsResetPasswordConfirmView.as_view(), name='reset_password_confirm'),
    path('reset-password-complete/', views.AccountsResetPasswordCompleteView.as_view(), name='reset_password_complete'),
    path('sign-up-started', views.SignUpStartedView.as_view(), name='sign_up_started'),
    path('complete-signup/<uuid:token>', views.CompleteSignUpView.as_view(), name='complete_signup'),

]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('browse', views.BrowseTemplateView.as_view(), name='browse'),
    path('shelves', views.ShelvesTemplateView.as_view(), name='shelves'),
    path('wishlist', views.WishlistTemplateView.as_view(), name='wishlist'),
    path('friends', views.FriendsTemplateView.as_view(), name='friends'),
    path('chat', views.ChatTemplateView.as_view(), name='chat'),
    path('profile', views.ProfileTemplateView.as_view(), name='profile'),
    path('settings', views.SettingsTemplateView.as_view(), name='settings'),
]

readwise/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('core.urls')),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from typing import Any
from django.shortcuts import render
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

class BrowseTemplateView(LoginRequiredMixin, TemplateView):
    template_name = 'core/browse.html'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        ctx = super().get_context_data(**kwargs)
        ctx['menu'] = 'browse'
        return ctx


class ShelvesTemplateView(LoginRequiredMixin, TemplateView):
    template_name = 'core/shelves.html'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        ctx = super().get_context_data(**kwargs)
        ctx['menu'] = 'shelves'
        return ctx

class WishlistTemplateView(LoginRequiredMixin, TemplateView):
    template_name = 'core/wishlist.html'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        ctx = super().get_context_data(**kwargs)
        ctx['menu'] = 'wishlist'
        return ctx

class FriendsTemplateView(LoginRequiredMixin, TemplateView):
    template_name = 'core/friends.html'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        ctx = super().get_context_data(**kwargs)
        ctx['menu'] = 'friends'
        return ctx

class ChatTemplateView(LoginRequiredMixin, TemplateView):
    template_name = 'core/chat.html'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        ctx = super().get_context_data(**kwargs)
        ctx['menu'] = 'chat'
        return ctx

class ProfileTemplateView(LoginRequiredMixin, TemplateView):
    template_name = 'core/profile.html'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        ctx = super().get_context_data(**kwargs)
        ctx['menu'] = 'profile'
        return ctx

class SettingsTemplateView(LoginRequiredMixin, TemplateView):
    template_name = 'core/settings.html'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        ctx = super().get_context_data(**kwargs)
        ctx['menu'] = 'settings'
        return ctx

core/templates/core/base.html
{% load static %}

<!doctype html>
<html lang="en" data-bs-theme="auto">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="" />
    <meta
      name="author"
      content="Mark Otto, Jacob Thornton, and Bootstrap contributors"
    />
    <meta name="generator" content="Astro v5.13.2" />
    <title>ReadWise</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <meta name="theme-color" content="#712cf9" />
    <link href="{% static 'core/css/sidebars.css' %}" rel="stylesheet" />
    <link href="{% static 'core/css/base.css' %}" rel="stylesheet" />
  </head>
  <body>
    <main class="d-flex flex-nowrap">
      <div
        class="d-flex flex-column flex-shrink-0 p-3 bg-body-tertiary"
        style="width: 280px; height: 100vh">
        <a
          href="/"
          class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
          <svg xmlns="http://www.w3.org/2000/svg" class="bi pe-none me-2 text-primary" width="40" height="32" fill="currentColor" class="bi bi-book" viewBox="0 0 16 16">
            <path d="M1 2.828c.885-.37 2.154-.769 3.388-.893 1.33-.134 2.458.063 3.112.752v9.746c-.935-.53-2.12-.603-3.213-.493-1.18.12-2.37.461-3.287.811zm7.5-.141c.654-.689 1.782-.886 3.112-.752 1.234.124 2.503.523 3.388.893v9.923c-.918-.35-2.107-.692-3.287-.81-1.094-.111-2.278-.039-3.213.492zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783"/>
          </svg>
          <span class="fs-4">ReadWise</span>
        </a>
        <hr />
        <ul class="nav nav-pills flex-column mb-auto">
          <li class="nav-item">
            <a href="{% url 'core:browse' %}" class="nav-link  {% if menu == 'browse' %} active {% else %} link-body-emphasis {% endif %}" aria-current="page">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-journal" viewBox="0 0 16 16">
                <path d="M3 0h10a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2v-1h1v1a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H3a1 1 0 0 0-1 1v1H1V2a2 2 0 0 1 2-2"/>
                <path d="M1 5v-.5a.5.5 0 0 1 1 0V5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1zm0 3v-.5a.5.5 0 0 1 1 0V8h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1zm0 3v-.5a.5.5 0 0 1 1 0v.5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1z"/>
              </svg>
              Browse Books
            </a>
          </li>
          <li>
            <a href="{% url 'core:shelves' %}" class="nav-link {% if menu == 'shelves' %} active {% else %} link-body-emphasis {% endif %}">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bookshelf" viewBox="0 0 16 16">
                <path d="M2.5 0a.5.5 0 0 1 .5.5V2h10V.5a.5.5 0 0 1 1 0v15a.5.5 0 0 1-1 0V15H3v.5a.5.5 0 0 1-1 0V.5a.5.5 0 0 1 .5-.5M3 14h10v-3H3zm0-4h10V7H3zm0-4h10V3H3z"/>
              </svg>
              My Shelves
            </a>
          </li>
          <li>
            <a href="{% url 'core:wishlist' %}" class="nav-link {% if menu == 'wishlist' %} active {% else %} link-body-emphasis {% endif %}">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bookmark" viewBox="0 0 16 16">
                <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.777.416L8 13.101l-5.223 2.815A.5.5 0 0 1 2 15.5zm2-1a1 1 0 0 0-1 1v12.566l4.723-2.482a.5.5 0 0 1 .554 0L13 14.566V2a1 1 0 0 0-1-1z"/>
              </svg>
              My Wishlist
            </a>
          </li>
          <li>
            <a href="{% url 'core:friends' %}" class="nav-link {% if menu == 'friends' %} active {% else %} link-body-emphasis {% endif %}">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-people" viewBox="0 0 16 16">
                <path d="M15 14s1 0 1-1-1-4-5-4-5 3-5 4 1 1 1 1zm-7.978-1L7 12.996c.001-.264.167-1.03.76-1.72C8.312 10.629 9.282 10 11 10c1.717 0 2.687.63 3.24 1.276.593.69.758 1.457.76 1.72l-.008.002-.014.002zM11 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4m3-2a3 3 0 1 1-6 0 3 3 0 0 1 6 0M6.936 9.28a6 6 0 0 0-1.23-.247A7 7 0 0 0 5 9c-4 0-5 3-5 4q0 1 1 1h4.216A2.24 2.24 0 0 1 5 13c0-1.01.377-2.042 1.09-2.904.243-.294.526-.569.846-.816M4.92 10A5.5 5.5 0 0 0 4 13H1c0-.26.164-1.03.76-1.724.545-.636 1.492-1.256 3.16-1.275ZM1.5 5.5a3 3 0 1 1 6 0 3 3 0 0 1-6 0m3-2a2 2 0 1 0 0 4 2 2 0 0 0 0-4"/>
              </svg>
              My Friends
            </a>
          </li>
          <li>
            <a href="{% url 'core:chat' %}" class="nav-link {% if menu == 'chat' %} active {% else %} link-body-emphasis {% endif %}">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat" viewBox="0 0 16 16">
                <path d="M2.678 11.894a1 1 0 0 1 .287.801 11 11 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8 8 0 0 0 8 14c3.996 0 7-2.807 7-6s-3.004-6-7-6-7 2.808-7 6c0 1.468.617 2.83 1.678 3.894m-.493 3.905a22 22 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a10 10 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9 9 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105"/>
              </svg>
              Chat 
            </a>
          </li>
          <li>
            <a href="{% url 'core:profile' %}" class="nav-link {% if menu == 'profile' %} active {% else %} link-body-emphasis {% endif %}">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person" viewBox="0 0 16 16">
                <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6m2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0m4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4m-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10s-3.516.68-4.168 1.332c-.678.678-.83 1.418-.832 1.664z"/>
              </svg>
              My Profile
            </a>
          </li>
          <li>
            <a href="{% url 'core:settings' %}" class="nav-link {% if menu == 'settings' %} active {% else %} link-body-emphasis {% endif %}">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-gear" viewBox="0 0 16 16">
                <path d="M8 4.754a3.246 3.246 0 1 0 0 6.492 3.246 3.246 0 0 0 0-6.492M5.754 8a2.246 2.246 0 1 1 4.492 0 2.246 2.246 0 0 1-4.492 0"/>
                <path d="M9.796 1.343c-.527-1.79-3.065-1.79-3.592 0l-.094.319a.873.873 0 0 1-1.255.52l-.292-.16c-1.64-.892-3.433.902-2.54 2.541l.159.292a.873.873 0 0 1-.52 1.255l-.319.094c-1.79.527-1.79 3.065 0 3.592l.319.094a.873.873 0 0 1 .52 1.255l-.16.292c-.892 1.64.901 3.434 2.541 2.54l.292-.159a.873.873 0 0 1 1.255.52l.094.319c.527 1.79 3.065 1.79 3.592 0l.094-.319a.873.873 0 0 1 1.255-.52l.292.16c1.64.893 3.434-.902 2.54-2.541l-.159-.292a.873.873 0 0 1 .52-1.255l.319-.094c1.79-.527 1.79-3.065 0-3.592l-.319-.094a.873.873 0 0 1-.52-1.255l.16-.292c.893-1.64-.902-3.433-2.541-2.54l-.292.159a.873.873 0 0 1-1.255-.52zm-2.633.283c.246-.835 1.428-.835 1.674 0l.094.319a1.873 1.873 0 0 0 2.693 1.115l.291-.16c.764-.415 1.6.42 1.184 1.185l-.159.292a1.873 1.873 0 0 0 1.116 2.692l.318.094c.835.246.835 1.428 0 1.674l-.319.094a1.873 1.873 0 0 0-1.115 2.693l.16.291c.415.764-.42 1.6-1.185 1.184l-.291-.159a1.873 1.873 0 0 0-2.693 1.116l-.094.318c-.246.835-1.428.835-1.674 0l-.094-.319a1.873 1.873 0 0 0-2.692-1.115l-.292.16c-.764.415-1.6-.42-1.184-1.185l.159-.291A1.873 1.873 0 0 0 1.945 8.93l-.319-.094c-.835-.246-.835-1.428 0-1.674l.319-.094A1.873 1.873 0 0 0 3.06 4.377l-.16-.292c-.415-.764.42-1.6 1.185-1.184l.292.159a1.873 1.873 0 0 0 2.692-1.115z"/>
              </svg>
              Settings
            </a>
          </li>
        </ul>
      </div>

      <div class="flex-grow-1">
        <header class="p-3 mb-3 border-bottom">
          <div class="container">
            <div
              class="d-flex justify-content-end"
            >
              <div class="dropdown text-end">
                <a
                  href="#"
                  class="d-block link-body-emphasis text-decoration-none dropdown-toggle"
                  data-bs-toggle="dropdown"
                  aria-expanded="false"
                >
                  <span class="me-4">{{ request.user.first_name }} {{ request.user.last_name }}</span>
                  <img
                    src="https://github.com/mdo.png"
                    alt="mdo"
                    width="32"
                    height="32"
                    class="rounded-circle"
                  />
                </a>
                <ul class="dropdown-menu text-small">
                  <li><a class="dropdown-item" href="#" onclick="onSignOut()">Sign out</a></li>
                  <form id="sign_out_form" method="post" action="{% url 'accounts:sign_out' %}">
                    {% csrf_token %}
                  </form>
                </ul>
              </div>
            </div>
          </div>
        </header>

        {% block body %} {% endblock body%}

      </div>

    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
    <script src="{% static 'core/js/sidebars.js' %}"></script>
    <script src="{% static 'core/js/core.js' %}"></script>
  </body>
</html>

core/templates/core/browse.html
{% extends 'core/base.html' %}

{% block body %} 
    <h3> Browse Coming Soon </h3>
{% endblock body %}

core/templates/core/chat.html
{% extends 'core/base.html' %}

{% block body %} 
    <h3> Chat Coming Soon! </h3>
{% endblock body %}

core/templates/core/friends.html
{% extends 'core/base.html' %}

{% block body %} 
    <h3> Friends Coming Soon! </h3>
{% endblock body %}

core/templates/core/profile.html
{% extends 'core/base.html' %}

{% block body %} 
    <h3> Profile Coming Soon! </h3>
{% endblock body %}

core/templates/core/settings.html
{% extends 'core/base.html' %}

{% block body %} 
    <h3> Settings Coming Soon! </h3>
{% endblock body %}

core/templates/core/shelves.html
{% extends 'core/base.html' %}

{% block body %} 
    <h3> Shelves Coming Soon! </h3>
{% endblock body %}

core/templates/core/wishlist.html
{% extends 'core/base.html' %}

{% block body %} 
    <h3> Wishlist Coming Soon! </h3>
{% endblock body %}